name: System under Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Nr. 1: 
    - name: Checkout Repository
      uses: actions/checkout@v3

      # Nr. 2:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3"

      # Nr. 3:
    - name: Install dependencies
      run: |
        cd v1.0.0
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Führe Flake8-Linting durch
      run: |
        cd v1.0.0
        flake8 .
      
    #- name: Run Pytests
    #  run: |
    #    cd v1.0.0
    #    python tests/pytests/app_tests.py
        
    #- name: Create Coverage Report
    #  run: |
    #    cd v1.0.0
    #    # coverage run -m pytest discover -s tests/unittests -p '*_tests.py'
    #    coverage run -m pytest tests/pytests/app_tests.py
    #    coverage report
    #    coverage xml -o coverage.xml
        
      # Nr. 5: Upload Coverage Report
    #- name: Upload Coverage Report
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: coverage-report
    #    path: v1.0.0/coverage.xml
      
      # Nr. 4:
    - name: Start Flask Application
      run: |
        cd v1.0.0
        python app.py &
        echo $! > flask_pid.txt

      # Nr. 6:
    - name: Stop Flask Application
      run: |
        pid=$(cat v1.0.0/flask_pid.txt)
        kill $pid
