name: System under Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Nr. 1: 
    - name: Checkout Repository
      uses: actions/checkout@v3

      # Nr. 2:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3"

      # Nr. 3:
    - name: Install dependencies
      run: |
        cd v1.0.0
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Unittest
      run: |
        cd v1.0.0
        python tests/unittests/app_tests.py
      
      # Nr. 4:
    - name: Start Flask Application
      run: |
        cd v1.0.0
        python app.py &
        echo $! > flask_pid.txt
        

      # Nr. 5:
    - name: Upload Coverage Report
      run: |
        cd v1.0.0
        coverage run --branch -m unittest discover
        coverage report

      # Nr. 6:
    - name: Stop Flask Application
      run: |
        pid=$(cat v1.0.0/flask_pid.txt)
        kill $pid
