name: System under Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f v1.0.0/requirements.txt ]; then pip install -r v1.0.0/requirements.txt; fi
      working-directory: /v1.0.0
    - name: Start Flask Application
      run: |
        python v1.0.0/app.py
      working-directory: /v1.0.0
